-------------------------------------------------------------------------------
-- step01_inventory.sql — 소스 DB 인벤토리 수집 (STEP 01: 1-1 ~ 1-4)
-- 실행 환경: [소스]
-- 접속 정보: ${SRC_DBA_USER}/${SRC_DBA_PASS}@${SRC_TNS}
-- 목적: 마이그레이션 범위와 리스크를 사전에 파악
-- 담당: 소스 DBA
-- 예상 소요: 30분
-------------------------------------------------------------------------------
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET PAGESIZE 1000
SET LINESIZE 300
SET TRIMSPOOL ON
SET FEEDBACK ON
SET HEADING ON
SET COLSEP '|'

SPOOL logs/step01_inventory.log

PROMPT =============================================
PROMPT [1-1] DB 기본 정보 확인
PROMPT =============================================

SELECT NAME, DB_UNIQUE_NAME, LOG_MODE, OPEN_MODE,
       PLATFORM_NAME, CDB
FROM V$DATABASE;

PROMPT =============================================
PROMPT [1-2] DB 용량 및 스키마별 크기
PROMPT =============================================

-- 전체 DB 사용량
SELECT ROUND(SUM(BYTES)/1024/1024/1024, 2) AS TOTAL_GB
FROM DBA_SEGMENTS;

-- 사용자 스키마별 용량
SELECT OWNER,
       ROUND(SUM(BYTES)/1024/1024/1024, 2) AS GB,
       COUNT(DISTINCT SEGMENT_NAME) AS SEG_CNT
FROM DBA_SEGMENTS
WHERE OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'DBSFWUSER','DVSYS','EXFSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB'
)
GROUP BY OWNER
ORDER BY 2 DESC;

PROMPT =============================================
PROMPT [1-3] 오브젝트 유형별 수량
PROMPT =============================================

SELECT OBJECT_TYPE, COUNT(*) AS CNT
FROM DBA_OBJECTS
WHERE OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'DBSFWUSER','DVSYS','EXFSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB','XS$NULL'
)
AND OBJECT_TYPE NOT IN ('JAVA CLASS','JAVA DATA','JAVA RESOURCE')
GROUP BY OBJECT_TYPE
ORDER BY OBJECT_TYPE;

PROMPT =============================================
PROMPT [1-4] 특수 오브젝트 현황 파악
PROMPT =============================================

PROMPT --- PK 없는 테이블 목록 (Supplemental Log 추가 대상) ---

SELECT T.OWNER, T.TABLE_NAME
FROM DBA_TABLES T
WHERE T.OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'DBSFWUSER','DVSYS','EXFSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB','XS$NULL',
    'GGADMIN','GGS_TEMP','MIGRATION_USER'
)
AND T.TEMPORARY = 'N'
AND T.EXTERNAL = 'NO'
AND NOT EXISTS (
    SELECT 1 FROM DBA_CONSTRAINTS C
    WHERE C.OWNER = T.OWNER AND C.TABLE_NAME = T.TABLE_NAME
    AND C.CONSTRAINT_TYPE = 'P'
)
ORDER BY T.OWNER, T.TABLE_NAME;

PROMPT --- LOB 컬럼 현황 ---

SELECT OWNER, TABLE_NAME, COLUMN_NAME, SECUREFILE
FROM DBA_LOBS
WHERE OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'DBSFWUSER','DVSYS','EXFSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB'
)
ORDER BY OWNER, TABLE_NAME;

PROMPT --- XMLTYPE 컬럼 테이블 (GG 복제 제외 검토 대상) ---

SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE DATA_TYPE IN ('XMLTYPE','SYS.XMLTYPE')
AND OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB'
);

PROMPT --- 파티션 테이블 현황 ---

SELECT OWNER, TABLE_NAME, PARTITIONING_TYPE,
       SUBPARTITIONING_TYPE, PARTITION_COUNT
FROM DBA_PART_TABLES
WHERE OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB'
)
ORDER BY OWNER, TABLE_NAME;

PROMPT --- MV 목록 및 REFRESH 방식 ---

SELECT OWNER, MVIEW_NAME, REFRESH_METHOD, REFRESH_MODE, STALENESS
FROM DBA_MVIEWS
WHERE OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB'
)
ORDER BY OWNER, MVIEW_NAME;

PROMPT --- DB Link 목록 ---

SELECT OWNER, DB_LINK, USERNAME, HOST FROM DBA_DB_LINKS
ORDER BY OWNER, DB_LINK;

PROMPT --- Directory Object 목록 ---

SELECT OWNER, DIRECTORY_NAME, DIRECTORY_PATH
FROM DBA_DIRECTORIES ORDER BY DIRECTORY_NAME;

PROMPT --- External Table 목록 ---

SELECT OWNER, TABLE_NAME, DEFAULT_DIRECTORY_NAME
FROM DBA_EXTERNAL_TABLES
WHERE OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS'
);

PROMPT --- DBMS_JOB 목록 ---

SELECT JOB, LOG_USER, WHAT, INTERVAL, BROKEN, NEXT_DATE
FROM DBA_JOBS ORDER BY JOB;

PROMPT --- BITMAP Index 목록 (SE 타겟 불가 -> 대체 필요) ---

SELECT OWNER, INDEX_NAME, TABLE_NAME, INDEX_TYPE
FROM DBA_INDEXES
WHERE INDEX_TYPE = 'BITMAP'
AND OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB'
);

PROMPT =============================================
PROMPT STEP 01 인벤토리 수집 완료
PROMPT =============================================

SPOOL OFF
EXIT
