-------------------------------------------------------------------------------
-- step05_create_accounts.sql — 소스/타겟 계정 생성 GGADMIN, MIGRATION_USER (STEP 05)
-- 실행 환경: [소스] + [타겟]
-- 접속 정보 (소스): ${SRC_DBA_USER}/${SRC_DBA_PASS}@${SRC_TNS}
-- 접속 정보 (타겟): ${TGT_DBA_USER}/${TGT_DBA_PASS}@${TGT_TNS}
-- 목적: GGADMIN, MIGRATION_USER 계정 생성 및 권한 부여
-- 담당: 소스 DBA + 타겟 DBA
-- 주의: 소스/타겟 각각 접속하여 해당 섹션 실행
--       <strong_password> 를 실제 패스워드로 교체할 것
-------------------------------------------------------------------------------
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET PAGESIZE 1000
SET LINESIZE 300
SET TRIMSPOOL ON
SET FEEDBACK ON
SET HEADING ON
SET ECHO ON

SPOOL logs/step05_create_accounts.log

PROMPT =============================================
PROMPT [5-1] 소스 RDS -- GGADMIN 계정 생성
PROMPT ※ 소스 DB에 접속하여 실행
PROMPT =============================================

-- [소스] GGADMIN 계정 생성 및 권한 부여
CREATE USER GGADMIN IDENTIFIED BY "<strong_password>"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE DEFAULT;

GRANT CREATE SESSION       TO GGADMIN;
GRANT ALTER SESSION        TO GGADMIN;
GRANT SELECT ANY DICTIONARY TO GGADMIN;
GRANT SELECT ANY TABLE     TO GGADMIN;
GRANT FLASHBACK ANY TABLE  TO GGADMIN;
GRANT EXECUTE ON DBMS_FLASHBACK TO GGADMIN;
GRANT SELECT ON V_$DATABASE         TO GGADMIN;
GRANT SELECT ON V_$LOG              TO GGADMIN;
GRANT SELECT ON V_$LOGFILE          TO GGADMIN;
GRANT SELECT ON V_$ARCHIVED_LOG     TO GGADMIN;
GRANT SELECT ON V_$LOG_HISTORY      TO GGADMIN;
GRANT SELECT ON V_$TRANSACTION      TO GGADMIN;
GRANT SELECT ON V_$SESSION          TO GGADMIN;

-- 패스워드 만료 방지 (만료 시 Extract ABEND)
-- RDS에서는 Profile 변경 대신 주기적 갱신 절차 수립

PROMPT --- GGADMIN 권한 확인 ---
SELECT GRANTEE, GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'GGADMIN';
SELECT GRANTEE, PRIVILEGE    FROM DBA_SYS_PRIVS  WHERE GRANTEE = 'GGADMIN';

PROMPT =============================================
PROMPT [5-2] 소스 RDS -- MIGRATION_USER 계정 생성
PROMPT ※ 소스 DB에 접속하여 실행
PROMPT =============================================

-- [소스] MIGRATION_USER 계정 생성
CREATE USER MIGRATION_USER IDENTIFIED BY "<strong_password>"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION        TO MIGRATION_USER;
GRANT CREATE TABLE          TO MIGRATION_USER;  -- STATS_EXPORT_TABLE 생성용
GRANT UNLIMITED TABLESPACE  TO MIGRATION_USER;
GRANT EXP_FULL_DATABASE     TO MIGRATION_USER;
GRANT SELECT_CATALOG_ROLE   TO MIGRATION_USER;
GRANT FLASHBACK ANY TABLE   TO MIGRATION_USER;
GRANT EXECUTE ON DBMS_STATS TO MIGRATION_USER;

PROMPT =============================================
PROMPT [5-3] 타겟 DBCS -- GGADMIN 계정 생성
PROMPT ※ 타겟 DB에 접속하여 실행
PROMPT =============================================

-- [타겟] GGADMIN 계정 생성
CREATE USER GGADMIN IDENTIFIED BY "<strong_password>"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION       TO GGADMIN;
GRANT ALTER SESSION        TO GGADMIN;
GRANT SELECT ANY DICTIONARY TO GGADMIN;
GRANT ALTER ANY TABLE      TO GGADMIN;
GRANT INSERT ANY TABLE     TO GGADMIN;
GRANT UPDATE ANY TABLE     TO GGADMIN;
GRANT DELETE ANY TABLE     TO GGADMIN;
GRANT SELECT ANY TABLE     TO GGADMIN;

-- 패스워드 무제한 설정 (만료 시 Replicat ABEND 방지)
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
-- 또는 GGADMIN 전용 Profile 생성 권장:
-- CREATE PROFILE GG_PROFILE LIMIT PASSWORD_LIFE_TIME UNLIMITED;
-- ALTER USER GGADMIN PROFILE GG_PROFILE;

PROMPT =============================================
PROMPT [5-4] 타겟 DBCS -- MIGRATION_USER 계정 생성
PROMPT ※ 타겟 DB에 접속하여 실행
PROMPT =============================================

-- [타겟] MIGRATION_USER 계정 생성
CREATE USER MIGRATION_USER IDENTIFIED BY "<strong_password>"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION        TO MIGRATION_USER;
GRANT CREATE TABLE          TO MIGRATION_USER;
GRANT UNLIMITED TABLESPACE  TO MIGRATION_USER;
GRANT IMP_FULL_DATABASE     TO MIGRATION_USER;
GRANT EXECUTE ON DBMS_STATS TO MIGRATION_USER;

PROMPT =============================================
PROMPT 계정 생성 최종 확인
PROMPT =============================================

PROMPT --- 소스 GGADMIN 권한 ---
SELECT GRANTEE, GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'GGADMIN';
SELECT GRANTEE, PRIVILEGE    FROM DBA_SYS_PRIVS  WHERE GRANTEE = 'GGADMIN';

PROMPT --- 소스 MIGRATION_USER 권한 ---
SELECT GRANTEE, GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'MIGRATION_USER';
SELECT GRANTEE, PRIVILEGE    FROM DBA_SYS_PRIVS  WHERE GRANTEE = 'MIGRATION_USER';

PROMPT =============================================
PROMPT STEP 05 계정 생성 완료
PROMPT =============================================

SPOOL OFF
EXIT
