-------------------------------------------------------------------------------
-- step02_static_schema.sql — 정적 구조 검증 (STEP 02, 38항목)
-- 실행 환경: [양쪽] — 소스/타겟 동일 쿼리 실행 후 MINUS 비교
-- 접속 정보: ${SRC_DBA_USER}/${SRC_DBA_PASS}@${SRC_TNS} (소스)
--            ${TGT_DBA_USER}/${TGT_DBA_PASS}@${TGT_TNS} (타겟)
-- 목적: 타겟 DB의 스키마 구조가 소스와 완전 일치하는지 검증
-- 담당: 소스/타겟 DBA
-- 예상 소요: 2~3시간
-- 참조: validation_plan.xlsx — 02_Static_Schema (38항목)
-------------------------------------------------------------------------------
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET PAGESIZE 1000
SET LINESIZE 300
SET TRIMSPOOL ON
SET FEEDBACK ON
SET HEADING ON
SET COLSEP '|'

SPOOL logs/step02_static_schema.log

PROMPT =============================================
PROMPT STEP 02. 정적 구조 검증 (02_Static_Schema — 38항목)
PROMPT =============================================

PROMPT
PROMPT =============================================
PROMPT [2-1] 테이블/컬럼 구조 비교 (#1~5)
PROMPT =============================================

-- [검증항목 SS-001~005] 테이블/컬럼 구조 비교
PROMPT
PROMPT --- 테이블/컬럼 전수 목록 (소스/타겟 각각 실행 후 MINUS 비교) ---
SELECT OWNER, TABLE_NAME, COLUMN_NAME, COLUMN_ID,
       DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, DATA_DEFAULT
FROM DBA_TAB_COLUMNS
WHERE OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'DBSFWUSER','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB','XS$NULL'
)
ORDER BY OWNER, TABLE_NAME, COLUMN_ID;
-- 소스 결과 MINUS 타겟 결과 → 기대값: 0건

PROMPT
PROMPT --- 테이블 압축 속성 비교 ---
SELECT OWNER, TABLE_NAME, COMPRESSION, COMPRESS_FOR
FROM DBA_TABLES
WHERE OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS')
AND COMPRESSION = 'ENABLED'
ORDER BY OWNER, TABLE_NAME;
-- 소스에 압축 테이블 존재 시 타겟도 동일 방식 적용 여부 확인

PROMPT
PROMPT =============================================
PROMPT [2-2] 인덱스 완전성 검증 (#6~9)
PROMPT =============================================

-- [검증항목 SS-006~009] 인덱스 완전성 검증
PROMPT
PROMPT --- ① 인덱스 전체 목록 비교 (Invisible 포함) ---
SELECT OWNER, INDEX_NAME, TABLE_NAME, INDEX_TYPE, UNIQUENESS, STATUS, VISIBILITY, PARTITIONED
FROM DBA_INDEXES
WHERE OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS')
ORDER BY OWNER, TABLE_NAME, INDEX_NAME;
-- 소스 MINUS 타겟 → 기대값: 0건

PROMPT
PROMPT --- ② 인덱스 컬럼 구성 비교 (컬럼 순서 포함) ---
SELECT INDEX_OWNER, INDEX_NAME, TABLE_NAME, COLUMN_POSITION, COLUMN_NAME, DESCEND
FROM DBA_IND_COLUMNS
WHERE INDEX_OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS')
ORDER BY INDEX_OWNER, INDEX_NAME, COLUMN_POSITION;

PROMPT
PROMPT --- ③ Function-Based Index (FBI) 표현식 비교 ---
SELECT INDEX_OWNER, INDEX_NAME, TABLE_NAME, COLUMN_POSITION, COLUMN_EXPRESSION, DESCEND
FROM DBA_IND_EXPRESSIONS
WHERE INDEX_OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS')
ORDER BY INDEX_OWNER, INDEX_NAME, COLUMN_POSITION;

PROMPT
PROMPT --- ④ 전체 인덱스 VALID 상태 (UNUSABLE 0건) ---
PROMPT [타겟] 실행
SELECT OWNER, INDEX_NAME, TABLE_NAME, STATUS, PARTITIONED
FROM DBA_INDEXES
WHERE STATUS NOT IN ('VALID','N/A')
AND OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS');
-- 기대값: 0건

PROMPT
PROMPT --- ⑤ 파티션 인덱스 파티션별 USABLE 확인 ---
PROMPT [타겟] 실행
SELECT INDEX_OWNER, INDEX_NAME, PARTITION_NAME, STATUS
FROM DBA_IND_PARTITIONS
WHERE STATUS != 'USABLE'
AND INDEX_OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS');
-- 기대값: 0건

PROMPT
PROMPT --- ⑥ 인덱스 통계 존재 여부 (LAST_ANALYZED IS NULL 0건) ---
PROMPT [타겟] 실행
SELECT OWNER, INDEX_NAME, TABLE_NAME, LAST_ANALYZED
FROM DBA_IND_STATISTICS
WHERE OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS')
AND LAST_ANALYZED IS NULL
ORDER BY OWNER, INDEX_NAME;
-- 기대값: 0건

PROMPT
PROMPT =============================================
PROMPT [2-3] 제약조건 검증 (#10~15)
PROMPT =============================================

-- [검증항목 SS-010~015] 제약조건 검증
PROMPT
PROMPT --- 제약조건 전수 비교 (PK/UK/FK/CHECK) ---
SELECT OWNER, CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE, STATUS,
       R_OWNER, R_CONSTRAINT_NAME, DELETE_RULE
FROM DBA_CONSTRAINTS
WHERE OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS')
AND CONSTRAINT_TYPE IN ('P','U','R','C')
ORDER BY OWNER, TABLE_NAME, CONSTRAINT_TYPE;
-- 소스 MINUS 타겟 → 기대값: 0건

PROMPT
PROMPT --- DISABLED 제약조건 확인 (FK 제외 — 복제 중 의도적 DISABLE) ---
PROMPT [타겟] 실행
SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM DBA_CONSTRAINTS
WHERE STATUS = 'DISABLED'
AND CONSTRAINT_TYPE != 'R'   -- FK는 제외 (복제 중 의도적 DISABLE)
AND OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS');
-- 기대값: 0건 (FK 외 PK/UK/CHECK는 DISABLED 없음)

PROMPT
PROMPT =============================================
PROMPT [2-4] 시퀀스 및 Synonym 검증 (#19~23)
PROMPT =============================================

-- [검증항목 SS-019~023] 시퀀스 및 Synonym 검증
PROMPT
PROMPT --- 시퀀스 전체 속성 비교 ---
SELECT SEQUENCE_OWNER, SEQUENCE_NAME,
       MIN_VALUE, MAX_VALUE, INCREMENT_BY,
       CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER
FROM DBA_SEQUENCES
WHERE SEQUENCE_OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS')
ORDER BY SEQUENCE_OWNER, SEQUENCE_NAME;
-- 타겟 LAST_NUMBER ≥ 소스 LAST_NUMBER + CACHE_SIZE 확인
-- INCREMENT_BY / CYCLE / ORDER / CACHE 소스와 완전 일치 확인

PROMPT
PROMPT --- Synonym 전수 비교 (Public 포함) ---
SELECT OWNER, SYNONYM_NAME, TABLE_OWNER, TABLE_NAME, DB_LINK
FROM DBA_SYNONYMS
WHERE (OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS') OR OWNER = 'PUBLIC')
ORDER BY OWNER, SYNONYM_NAME;
-- 소스 MINUS 타겟 → 기대값: 0건

PROMPT
PROMPT --- 참조 객체 없는 Synonym (Dangling Synonym) ---
PROMPT [타겟] 실행
SELECT S.OWNER, S.SYNONYM_NAME, S.TABLE_OWNER, S.TABLE_NAME
FROM DBA_SYNONYMS S
WHERE NOT EXISTS (
    SELECT 1 FROM DBA_OBJECTS O
    WHERE O.OWNER = S.TABLE_OWNER AND O.OBJECT_NAME = S.TABLE_NAME
)
AND S.DB_LINK IS NULL
AND S.OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS');
-- 기대값: 0건

PROMPT
PROMPT =============================================
PROMPT [2-5] 사용자/권한 비교 (#29~32)
PROMPT =============================================

-- [검증항목 SS-029~032] 사용자/권한 비교
PROMPT
PROMPT --- 사용자 목록 및 Profile ---
SELECT USERNAME, ACCOUNT_STATUS, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE, PROFILE
FROM DBA_USERS
WHERE USERNAME NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'DBSFWUSER','DVSYS','GGSYS','GSMADMIN_INTERNAL','GSMCATUSER',
    'GSMUSER','LBACSYS','OJVMSYS','OLAPSYS','ORACLE_OCM','ORDDATA',
    'ORDPLUGINS','ORDSYS','SI_INFORMTN_SCHEMA','SYS$UMF','SYSBACKUP',
    'SYSDG','SYSKM','SYSRAC','WMSYS','XDB','XS$NULL'
)
ORDER BY USERNAME;

PROMPT
PROMPT --- 롤 부여 현황 비교 ---
SELECT GRANTEE, GRANTED_ROLE, ADMIN_OPTION FROM DBA_ROLE_PRIVS
WHERE GRANTEE NOT IN ('SYS','SYSTEM','DBA','IMP_FULL_DATABASE','EXP_FULL_DATABASE')
ORDER BY GRANTEE, GRANTED_ROLE;

PROMPT
PROMPT --- 시스템 권한 비교 ---
SELECT GRANTEE, PRIVILEGE, ADMIN_OPTION FROM DBA_SYS_PRIVS
WHERE GRANTEE NOT IN ('SYS','SYSTEM','DBA','IMP_FULL_DATABASE','EXP_FULL_DATABASE')
ORDER BY GRANTEE, PRIVILEGE;

PROMPT
PROMPT --- 객체 권한 비교 ---
SELECT GRANTEE, OWNER, TABLE_NAME, PRIVILEGE, GRANTABLE FROM DBA_TAB_PRIVS
WHERE GRANTEE NOT IN ('SYS','SYSTEM','DBA','PUBLIC','WMSYS')
ORDER BY GRANTEE, OWNER, TABLE_NAME;

PROMPT
PROMPT =============================================
PROMPT [2-6] INVALID 객체 0건 확인 (#37~38)
PROMPT =============================================

-- [검증항목 SS-037~038] INVALID 객체
PROMPT
PROMPT --- INVALID 객체 전수 확인 ---
PROMPT [타겟] 실행
SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, STATUS, LAST_DDL_TIME
FROM DBA_OBJECTS
WHERE STATUS = 'INVALID'
AND OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'DBSFWUSER','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB'
)
ORDER BY OWNER, OBJECT_TYPE;
-- 기대값: 0건 → INVALID 있으면 즉시 재컴파일

PROMPT
PROMPT --- INVALID 존재 시 전체 DB 재컴파일 (수동 실행) ---
PROMPT 아래 PL/SQL 블록은 INVALID 객체 발견 시에만 수동 실행하십시오:
PROMPT
PROMPT BEGIN
PROMPT     FOR u IN (
PROMPT         SELECT USERNAME FROM DBA_USERS
PROMPT         WHERE USERNAME NOT IN (
PROMPT             'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
PROMPT             'DBSFWUSER','DVSYS','EXFSYS','GGSYS','GSMADMIN_INTERNAL','GSMCATUSER',
PROMPT             'GSMUSER','LBACSYS','MDSYS','OJVMSYS','OLAPSYS','ORACLE_OCM','ORDDATA',
PROMPT             'ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SI_INFORMTN_SCHEMA',
PROMPT             'SYS$UMF','SYSBACKUP','SYSDG','SYSKM','SYSRAC','WMSYS','XDB','XS$NULL',
PROMPT             'GGADMIN','GGS_TEMP','MIGRATION_USER'
PROMPT         )
PROMPT         AND ACCOUNT_STATUS = 'OPEN'
PROMPT         ORDER BY USERNAME
PROMPT     ) LOOP
PROMPT         DBMS_UTILITY.COMPILE_SCHEMA(schema => u.USERNAME, compile_all => FALSE);
PROMPT     END LOOP;
PROMPT END;
PROMPT /

PROMPT
PROMPT --- 재컴파일 후 INVALID 재확인 ---
SELECT COUNT(*) AS INVALID_CNT FROM DBA_OBJECTS
WHERE STATUS = 'INVALID'
AND OWNER NOT IN (
    'SYS','SYSTEM','OUTLN','DBSNMP','APPQOSSYS','AUDSYS','CTXSYS',
    'DBSFWUSER','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS',
    'MDSYS','OJVMSYS','OLAPSYS','ORDDATA','ORDSYS','WMSYS','XDB'
);

PROMPT
PROMPT =============================================
PROMPT STEP 02 정적 구조 검증 완료
PROMPT =============================================

SPOOL OFF
EXIT
